language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . -q

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 9.0.2

branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: always
    on_failure: always
